config/routes.rb
Blog::Application.routes.draw do
  resources :posts

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	# relations
  belongs_to :post

  # validations
  validates :content, presence: true

  # scopes
  default_scope  { order(:created_at => :desc) }
end

app/models/post.rb
class Post < ActiveRecord::Base
	# relations
  has_many :comments, :dependent => :destroy

  # validations
  validates :body, presence: true

  # scopes
  default_scope  { order(:created_at => :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ActionController::Base





  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :new]

  # GET /posts/1/comments/1
  # GET /posts/1/comments/1.json
  def show
    #@comments = Comment.where(post_id: @post.id)
  end

  # GET /posts/1/comments/new
  def new
    @comment = Comment.new
  end

  # GET /posts/1/comments/edit
  def edit
  end

  # POST /posts/1/comments
  # POST /posts/1/comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:content))
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path({id:@comment.post_id}), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1/comments/1
  # PATCH/PUT /posts/1/comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_comment_path({id: @comment.id, post_id:@comment.post_id}), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1/comments/1
  # DELETE /posts/1/comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      if @comment
        @post = Post.find(@comment.post_id)
      elsif params[:id]
        @post = Post.find(params[:id])
      else
        @post = Post.find(params[:post_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.where(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.text_field :content, value: @comment.content %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit Comment</h3>

<%= form_for [@post, @comment] do |f| %>
  <%= f.text_field :content, value: @comment.content %>
  <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<h3>New Comment</h3>

<%= form_for [@post, @comment] do |f| %>
  <%= f.text_field :content, placeholder: "enter comment"%>
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<p>
  <strong><%= @comment.content %></strong>
</p>


<%= link_to 'Edit', edit_post_comment_path({id: @comment.id}) %> |
<%= button_to 'Destroy', {action: 'destroy', controller: 'comments'}, method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to 'Back', @post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="page-header">
  <h1>All Posts</h1>
</div>

<%= link_to "New Post", new_post_path, class: "btn btn-success" %>

<% @posts.each do |post| %>
<div class= "post">
   <strong><%=post.title%></strong>
   <p><%=post.body%></p>
   <div class= "meta">
     <%=link_to time_ago_in_words(post.created_at)+ " ago", post%>
     <span class="admin">
       | <%= link_to "Edit", edit_post_path(post)%> |
       <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %>
     </span>
     </br>
     </div>
   </div>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <table>
    <tr><td><strong>Comments:</strong></td></tr>

    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', post_comment_path({id: comment.id, post_id: comment.post_id}) %></td>
      </tr>
    <% end %>
  </table
</p>

<%= link_to 'New Comment', new_post_comment_path(@post) %> |
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>